// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-my-releases.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_releases_default = defineTool({
  name: "list_my_releases",
  title: "List my releases",
  description: "List releases owned by the signed-in artist, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)."),
    status: z.string().optional().describe("Optional status filter (e.g. pending, approved, live, rejected).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("releases").select("id,title,artist_name,status,release_date,upc,isrc,cover_art_url,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { releases: data } };
  }
});

// src/lib/mcp/tools/get-release.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_release_default = defineTool2({
  name: "get_release",
  title: "Get release details",
  description: "Fetch full details for a release the caller can access, including its tracks.",
  inputSchema: { release_id: z2.string().uuid().describe("Release UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ release_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb2(ctx);
    const { data: release, error } = await client.from("releases").select("*").eq("id", release_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!release) return { content: [{ type: "text", text: "Release not found or access denied." }], isError: true };
    const { data: tracks } = await client.from("release_tracks").select("*").eq("release_id", release_id).order("track_number");
    const payload = { release, tracks: tracks ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/get-my-earnings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_earnings_default = defineTool3({
  name: "get_my_earnings",
  title: "Get my earnings summary",
  description: "Return the signed-in artist's wallet balance, total earnings, available balance and recent monthly earnings.",
  inputSchema: {
    months: z3.number().int().min(1).max(36).optional().describe("How many recent months to include (default 12).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ months }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb3(ctx);
    const uid = ctx.getUserId();
    const { data: artist, error: aErr } = await client.from("artists").select("id,name,account_name,available_balance,total_earnings,wallet_balance,credit_balance").eq("id", uid).maybeSingle();
    if (aErr) return { content: [{ type: "text", text: aErr.message }], isError: true };
    const { data: monthly } = await client.from("monthly_artist_earnings").select("period_year,period_month,total_streams,total_earnings,currency").eq("artist_id", uid).order("period_year", { ascending: false }).order("period_month", { ascending: false }).limit(months ?? 12);
    const { data: summary } = await client.rpc("get_artist_stream_summary", { p_artist_id: uid });
    const payload = { artist, monthly: monthly ?? [], stream_summary: summary };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-my-withdrawals.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_withdrawals_default = defineTool4({
  name: "list_my_withdrawals",
  title: "List my withdrawals",
  description: "List the signed-in artist's withdrawal requests, most recent first.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)."),
    status: z4.string().optional().describe("Optional status filter (PENDING, APPROVED, COMPLETED, REJECTED).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb4(ctx).from("withdrawals").select("id,amount,naira_amount,status,account_name,account_number,bank_name,created_at,processed_at,approved_at,rejection_reason").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { withdrawals: data } };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's profile, role list, and linked artist record.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb5(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile }, { data: roles }, { data: artist }] = await Promise.all([
      client.from("profiles").select("*").eq("user_id", uid).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", uid),
      client.from("artists").select("id,name,email,account_name,status,available_balance,total_earnings").eq("id", uid).maybeSingle()
    ]);
    const payload = { user_id: uid, email: ctx.getUserEmail(), profile, roles: (roles ?? []).map((r) => r.role), artist };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-my-transactions.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_transactions_default = defineTool6({
  name: "list_my_transactions",
  title: "List my income transactions",
  description: "List the signed-in artist's income/royalty ledger transactions, most recent first.",
  inputSchema: {
    limit: z5.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb6(ctx).from("income_transactions").select("id,type,amount,balance_after,description,created_at,track_id,platform_id").eq("artist_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { transactions: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hewyffhdykietximpfbu";
var mcp_default = defineMcp({
  name: "malpinohdistro-mcp",
  title: "MALPINOHDISTRO",
  version: "0.1.0",
  instructions: "Tools for the MALPINOHDISTRO music distribution platform. Use these to read the signed-in artist's releases, earnings, withdrawals, transactions, and profile. All calls act as the signed-in Supabase user under RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_releases_default, get_release_default, get_my_earnings_default, list_my_withdrawals_default, get_my_profile_default, list_my_transactions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
